# Generated by Django 5.2.5 on 2025-09-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=25)),
                ('guest_surname', models.CharField(max_length=25)),
                ('guest_count', models.IntegerField()),
                ('reservation_time', models.TimeField()),
                ('guest_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
