# Generated by Django 5.2.5 on 2025-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
