# Generated by Django 5.2.5 on 2025-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_dish_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.CharField(max_length=25),
        ),
    ]
